export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACES_ID =
  process.env.NEXT_PUBLIC_APPWRITE_WORKSPACE_COLLECTION_ID!;
export const IMAGES_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!;
export const MEMBERS_ID =
  process.env.NEXT_PUBLIC_APPWRITE_MEMBERS_COLLECTION_ID!;
export const PROJECTS_ID =
  process.env.NEXT_PUBLIC_APPWRITE_PROJECT_COLLECTION_ID!;
